import JSZip from "jszip";
import type { DocumentFile, DesignFile, ResearchData } from "@/lib/types";

interface ZipOptions {
  projectName: string;
  documents: DocumentFile[];
  research?: ResearchData;
  designFiles?: DesignFile[];
}

export async function createProjectZip({
  projectName,
  documents,
  research,
  designFiles,
}: ZipOptions): Promise<Blob> {
  const zip = new JSZip();

  const safeName = projectName.replace(/[^a-zA-Z0-9가-힣\-_]/g, "_") || "project";
  const root = zip.folder(safeName);
  if (!root) throw new Error("Failed to create zip root folder");

  // docs/ folder — generated planning documents
  const docsFolder = root.folder("docs");
  if (docsFolder) {
    for (const doc of documents) {
      if (doc.status === "completed" && doc.content) {
        docsFolder.file(doc.filename, doc.content);
      }
    }
  }

  // research/ folder
  if (research && research.status === "completed") {
    const researchFolder = root.folder("research");
    if (researchFolder) {
      const researchMd = buildResearchMarkdown(research);
      researchFolder.file("market-research.md", researchMd);

      if (research.sources.length > 0) {
        const sourcesJson = JSON.stringify(research.sources, null, 2);
        researchFolder.file("sources.json", sourcesJson);
      }
    }
  }

  // design/ folder
  if (designFiles && designFiles.length > 0) {
    const designFolder = root.folder("design");
    if (designFolder) {
      for (const file of designFiles) {
        designFolder.file(file.filename, `<!-- Design file: ${file.url} -->`);
      }
    }
  }

  // README.md
  const readme = buildReadme(projectName, documents, research, designFiles);
  root.file("README.md", readme);

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

function buildResearchMarkdown(research: ResearchData): string {
  const { results } = research;
  const sections: string[] = ["# 업계 조사 리포트\n"];

  if (results.market_analysis) {
    sections.push(`## 시장 분석\n\n${results.market_analysis}\n`);
  }
  if (results.competitor_analysis) {
    sections.push(`## 경쟁사 분석\n\n${results.competitor_analysis}\n`);
  }
  if (results.korean_market) {
    sections.push(`## 한국 시장 특성\n\n${results.korean_market}\n`);
  }
  if (results.tech_trends) {
    sections.push(`## 기술 트렌드\n\n${results.tech_trends}\n`);
  }

  return sections.join("\n");
}

function buildReadme(
  projectName: string,
  documents: DocumentFile[],
  research?: ResearchData,
  designFiles?: DesignFile[]
): string {
  const completedDocs = documents.filter((d) => d.status === "completed");
  const now = new Date().toLocaleDateString("ko-KR");

  const docList = completedDocs
    .map((d) => `- \`docs/${d.filename}\` — ${getDocLabel(d.doc_type)}`)
    .join("\n");

  const researchSection =
    research?.status === "completed"
      ? `\n## 업계 조사\n\n- \`research/market-research.md\` — 시장/경쟁사/트렌드 분석\n- \`research/sources.json\` — 참고 출처\n`
      : "";

  const designSection =
    designFiles && designFiles.length > 0
      ? `\n## 디자인 산출물\n\n${designFiles.map((f) => `- \`design/${f.filename}\``).join("\n")}\n`
      : "";

  return `# ${projectName}

> DevPlan Generator로 자동 생성된 프로젝트 계획서입니다.
> 생성일: ${now}

## 문서 목록

${docList || "생성된 문서가 없습니다."}
${researchSection}${designSection}
## 사용 방법

1. \`docs/CLAUDE.md\` 를 Claude Code 컨텍스트로 로드하세요.
2. 각 스펙 문서를 참조하여 개발을 시작하세요.
3. UI 메뉴 트리 기반으로 컴포넌트를 설계하세요.

---
*Generated by [DevPlan Generator](https://devplan-generator.vercel.app)*
`;
}

function getDocLabel(docType: DocumentFile["doc_type"]): string {
  const labels: Record<DocumentFile["doc_type"], string> = {
    claude_md: "프로젝트 메인 컨텍스트 (CLAUDE.md)",
    feature_spec: "기능 상세 스펙",
    api_design: "API 설계 문서",
    database_schema: "DB 스키마 설계",
    ui_menu_tree: "UI 메뉴 트리",
    dev_timeline: "개발 일정",
    tech_stack: "기술 스택 문서",
  };
  return labels[docType] || docType;
}
